name: build and integration test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: builds image
        env:
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          PEXEL_API_KEY: ${{ secrets.PEXEL_API_KEY }}
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install curl
          cd $GITHUB_WORKSPACE 
          docker build -t pixel-helper-api:build .
